# Generated by Django 3.2.5 on 2021-07-13 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advmodels', '0002_auto_20210713_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advmodels.album'),
        ),
    ]
