# Generated by Django 3.2.5 on 2021-07-16 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advmodels', '0004_alter_song_album'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
