# Generated by Django 3.2.5 on 2021-07-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxsample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polls', models.ManyToManyField(to='ajaxsample.Poll')),
            ],
        ),
    ]
