# Generated by Django 3.2.5 on 2021-07-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group_taskModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='groupModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='subTaskModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='taskModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('pority', models.IntegerField(choices=[(0, 'بی اهمیت'), (1, 'کم اهمیت'), (2, 'توجه'), (3, 'قابل توجه'), (4, 'مهم'), (5, 'ضروری')])),
                ('status', models.CharField(choices=[('disable', 'غیرفعال'), ('enable', 'فعال'), ('doing', 'در حال انجام'), ('done', 'انجام شده'), ('expire', 'منقضی'), ('archive', 'ارشیو'), ('unkown', 'بی سرپرست')], max_length=10)),
                ('type_task', models.IntegerField(choices=[('reminder', 'یادآور'), ('task', 'تسک')], max_length=10)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='taskperiodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
