# Generated by Django 3.2.5 on 2021-07-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodels',
            name='type_task',
            field=models.CharField(choices=[('reminder', 'یادآور'), ('task', 'تسک')], max_length=10),
        ),
    ]
