# Generated by Django 3.2.5 on 2021-07-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_taskmodels_type_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodels',
            name='pority',
            field=models.IntegerField(choices=[(0, 'بی اهمیت'), (1, 'کم اهمیت'), (2, 'توجه'), (3, 'قابل توجه'), (4, 'مهم'), (5, 'ضروری')], default=4),
        ),
    ]
