# Generated by Django 3.2.5 on 2021-07-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_taskmodels_pority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodels',
            name='status',
            field=models.CharField(choices=[('disable', 'غیرفعال'), ('enable', 'فعال'), ('doing', 'در حال انجام'), ('done', 'انجام شده'), ('expire', 'منقضی'), ('archive', 'ارشیو'), ('unkown', 'بی سرپرست')], default='enable', max_length=10),
        ),
        migrations.AlterField(
            model_name='taskmodels',
            name='type_task',
            field=models.CharField(choices=[('reminder', 'یادآور'), ('task', 'تسک')], default='task', max_length=10),
        ),
    ]
