# Generated by Django 3.2.5 on 2021-07-13 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0006_auto_20210713_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_taskmodels',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group_taskmodels',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.groupmodels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group_taskmodels',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.taskmodels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group_taskmodels',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subtaskmodels',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.taskmodels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskmodels',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
