# Generated by Django 3.2.5 on 2021-07-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_testfieldsmoels_error_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfieldsmoels',
            name='DateTimeField',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testfieldsmoels',
            name='dateFeild',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testfieldsmoels',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testfieldsmoels',
            name='error_messages',
            field=models.CharField(error_messages={'blank': 'نکن این کار رو با ما', 'null': 'چشم'}, max_length=500),
        ),
        migrations.AlterField(
            model_name='testfieldsmoels',
            name='help_text',
            field=models.CharField(max_length=500, verbose_name='توضیح اضافی'),
        ),
    ]
