# Generated by Django 3.2.5 on 2021-07-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20210713_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodels',
            options={'ordering': ['created_at'], 'verbose_name': 'تسک', 'verbose_name_plural': 'تسک ها'},
        ),
    ]
