# Generated by Django 3.2.5 on 2021-07-15 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_auto_20210714_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testfieldsmoels',
            options={'ordering': ['DateTimeField'], 'verbose_name': 'تست فیلد', 'verbose_name_plural': 'تست فیلدها'},
        ),
    ]
