# Generated by Django 3.2.5 on 2021-07-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_auto_20210715_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='lastName',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='phoneNumber',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
    ]
