# Generated by Django 3.2.5 on 2021-07-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='username',
        ),
    ]
