# Generated by Django 3.2.5 on 2021-07-16 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Username',
        ),
    ]
